version: "2"
services:
  auth:
    container_name: auth
    restart: always
    build: auth
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network

  books:
    container_name: books
    restart: always
    build: books
    ports:
      - "4000:4000"
    depends_on: 
      - redis
    networks:
      - nodeapp-network
 
  redis:
    container_name: redis
    image: "redis:alpine"
    networks:
      - nodeapp-network
      
  server:
    container_name: server
    restart: always
    build: server
    ports:
      - "8099:8099"
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
