version: "2"
services:
  auth:
    container_name: auth
    restart: always
    build: auth
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network

  books:
    container_name: books
    restart: always
    build: books
    ports:
      - "4000:4000"
    depends_on: 
      - mongo
    networks:
      - nodeapp-network

  mongo:
    container_name: mongo
    image: mongo:4
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: [--auth]
    #volumes:
    #  - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - nodeapp-network

  mongoseed:
    build: ./dbseed
    links:
      - mongo
    networks:
      - nodeapp-network

  server:
    container_name: server
    restart: always
    build: server
    ports:
      - "8099:8099"
    depends_on: 
      - auth
      - books
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
